import os
from setuptools import setup


def _install_conda_fontconfig_hook():
    # conda-forge's vtk/pyqt combo can segfault inside libfontconfig when the
    # shared ~/.cache/fontconfig directory holds cache files written by other
    # fontconfig versions (system fontconfig, other conda envs). When we are
    # being installed into a conda env, drop an activation hook that isolates
    # this env's font cache. Outside conda there is no CONDA_PREFIX, so this
    # is a no-op (this is the `pip install .` path documented in the README;
    # `environment.yml`'s `variables:` block covers the `conda env create`
    # path — both write the same value, which is harmless if both fire).
    conda_prefix = os.environ.get('CONDA_PREFIX')
    if not conda_prefix or not os.path.isdir(conda_prefix):
        return
    activate_dir = os.path.join(conda_prefix, 'etc', 'conda', 'activate.d')
    deactivate_dir = os.path.join(conda_prefix, 'etc', 'conda', 'deactivate.d')
    activate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by ccdaf setup.py: isolate the fontconfig cache to\n'
        '# avoid crashes from cross-version cache corruption in the shared\n'
        '# ~/.cache/fontconfig directory.\n'
        'export _CCDAF_OLD_XDG_CACHE_HOME="${XDG_CACHE_HOME}"\n'
        'export XDG_CACHE_HOME="${HOME}/.cache/ccdaf-fontconfig"\n'
    )
    deactivate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by ccdaf setup.py: restore XDG_CACHE_HOME.\n'
        'if [ -n "${_CCDAF_OLD_XDG_CACHE_HOME}" ]; then\n'
        '    export XDG_CACHE_HOME="${_CCDAF_OLD_XDG_CACHE_HOME}"\n'
        'else\n'
        '    unset XDG_CACHE_HOME\n'
        'fi\n'
        'unset _CCDAF_OLD_XDG_CACHE_HOME\n'
    )
    try:
        os.makedirs(activate_dir, exist_ok=True)
        os.makedirs(deactivate_dir, exist_ok=True)
        with open(os.path.join(activate_dir, 'zzz_ccdaf_fontconfig_cache.sh'), 'w') as f:
            f.write(activate_sh)
        with open(os.path.join(deactivate_dir, 'zzz_ccdaf_fontconfig_cache.sh'), 'w') as f:
            f.write(deactivate_sh)
        print('ccdaf: wrote conda fontconfig cache activation hook under {}'.format(activate_dir))
    except OSError as err:
        print('ccdaf: could not write conda fontconfig cache hook ({})'.format(err))


setup()

_install_conda_fontconfig_hook()
